### ISSUE TITLE
Make google sheets not publicly editable

### ISSUE THREAD

**Issue by sigaloid** [nalinbhardwaj/shiit-coin#2]
Right now we are doing a little trolling.
![image](https://user-images.githubusercontent.com/69441971/134838561-40baa981-24a9-48f9-9b49-da30cb97cdb0.png)
Highly recommended you lock this page :frowning: (unless that's by design!)

update: Locked :cry: feel free to close, repo owners!
![image](https://user-images.githubusercontent.com/69441971/134838798-9a82cb37-a1f8-4bfa-bf64-263ca15b375f.png)

**Comment by nalinbhardwaj** [comment]
Great catch @sigaloid fixed now!!

I've made a Community Chat Box for those still interested in sticking around haha
